Added Auto Connect and Default Pattern functionality
tuanchris/dune-weaver pull request #3
Opened 2024-12-26 18:54 UTC by Thokoop

Key changes:

- When starting app.py it'll automatically connect to first available serial port. 
- If a default_pattern.thr file is found in the ./patterns/custom_patterns/ folder, it will execute that on first boot
- A selected pattern can be set with the 'Set as default pattern' in the pattern file list, it will then be copied over to the custom_patterns/default_pattern.thr 
- Minor UX/UI improvements on the frontend (for example only showing certain buttons depending on the state) 

Tested on:
- Raspberry pi 2 model B (running app.py directly instead of via docker)

I'm not really experienced in python so please let me if there is something for me to improve.

I also took the liberty to add a footer with links to the github repo but feel free to not merge that if you don't like it.

2025-01-07 22:43 UTC, tuanchris requested changes
Hi @Thokoop Thank you for the PR. Sorry it took me some time to get to this. I left some comments, are you able to make these changes?

2025-01-07 22:43 UTC, tuanchris commented on app.py
> +        threading.Thread(target=trigger_default_pattern, daemon=True).start()
I think we should run the app first before trying to connect to the serial. If I don't have a device connected, the UI won't be up until the retries finish.

2025-01-07 22:43 UTC, tuanchris commented on app.py
> +        return jsonify({"success": False, "error": str(e)}), 500
Can you make this optional? I don't imagine everyone would want to run a default pattern every time.

2025-01-07 22:49 UTC, tuanchris commented on app.py
> +        return jsonify({"success": False, "error": str(e)}), 500
We can also merge this feature with the playlist functionality once we get to that point.

2025-01-07 23:58 UTC, Thokoop commented on app.py
> +        return jsonify({"success": False, "error": str(e)}), 500
This default pattern function is optional in the sense that it will only run if there is a file 'default_pattern.thr' found in ./patterns/custom_patterns/  
If not it won't execute it. 

The function 
@app.route('/set_default_pattern', methods=['POST'])
just handles the copying of the pattern file  that is selected on the frontend to this custom_patterns/default_pattern.thr file 

But it makes sense to merge this functionality later indeed with the playlist functionality. After the last changes from Main I found that it was a bit unreliable. Could be due to my old raspberry though but it doesn't make sense to debug it now when there are some bigger changes coming up.

2025-01-08 00:18 UTC, Thokoop commented on app.py
> +        threading.Thread(target=trigger_default_pattern, daemon=True).start()
Good point. I'll change it

2025-01-08 00:23 UTC, Thokoop commented
I've processed the feedback. It makes sense to wait a little with the default pattern functionality. I haven't fully retested but will do it tomorrow.

2025-01-12 02:24 UTC, merged